version: 18
jobs:
- name: Pull From Github
  steps:
  - !PullRepository
    name: Pull Form Github
    remoteUrl: https://github.com/zzflsxygod/godot.git
    syncToChildProject: false
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
